---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on centos
      yum:
        name: chrony
        state: present
      when: ansible_distribution == "CentOS" # decision making condition

    - name: Install ntp agent on ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes # actually it is like apt update so that ntp can be installed in ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: Start service on centos
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
    - name: Start service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
